### ISSUE TITLE
Quick-fix : Analyzing Documents with TF-IDF 

### ISSUE THREAD

**Issue by datalogism** [programminghistorian/ph-submissions#476] opened 2022-04-18 08:53 UTC
Hello the English team,

By reviewing the translation of a tutorial, I spotted a problem with the mathematical formulas :
http://programminghistorian.org/en/lessons/analyzing-documents-with-tfidf#how-to-run-it-in-python-3

I thing that is not a big issue, but i preferred to open a ticket than fixing it quickly without notifying you.

Is it a better way for preventing that kind of problems ? 

All the best,

**Comment by spapastamkou** [comment] 2022-04-18 10:11
@datalogism You need to open a ticket [on jekyll ](https://github.com/programminghistorian/jekyll/issues) since this is an already published lesson, choose the label "lesson maintenance" and assign it to Anisa. In this new ticket, you should also describe what the problem is and what is the solution you propose, if any. I will close this ticket here to avoid confusion. Thanks!

**Closed as completed by spapastamkou** 2022-04-18 10:11 UTC
Labels: English
