### ISSUE TITLE
Data, Dialogue, and AI: Exploring Text Collections with Large Language Models via Retrieval Augmented Generation

### ISSUE THREAD

**Issue by hawc2** [programminghistorian/ph-submissions#611] opened 2024-03-19 17:18 UTC
Programming Historian in English has received a proposal for a lesson, 'From Data to Dialogue: Exploring Text Collections with Large Language Models via Retrieval Augmented Generation' by @Dr-Hutchinson. 

I have circulated this proposal for feedback within the English team. We have considered this proposal for:

- **Openness**: we advocate for use of open source software, open programming languages and open datasets
- **Global access**: we serve a readership working with different operating systems and varying computational resources
- **Multilingualism**: we celebrate methodologies and tools that can be applied or adapted for use in multilingual research-contexts
- **Sustainability**: we're committed to publishing learning resources that can remain useful beyond present-day graphical user interfaces and current software versions

**We are pleased to have invited @Dr-Hutchinson to develop this Proposal into a Submission to be developed under the guidance of @jrladd  as editor**.

The Submission package should include:

- Lesson text (written in Markdown)
  - For guidance, we recommend Sarah Simpkin's lesson [Getting Started with Markdown]
- Figures: images / plots / graphs (if using)
- Data assets: codebooks, sample dataset (if using)

We ask @Dr-Hutchinson to share their Submission package with [our Publishing team by email](mailto:admin@programminghistorian.org), copying in @jrladd. 

We've agreed a submission date of April. We ask @Dr-Hutchinson to contact us if they need to revise this deadline. 

_When the Submission package is received_, our Publishing team will process the new lesson materials, and prepare a Preview of the initial draft. They will post a comment in this Issue to provide the locations of all key files, as well as a link to the Preview where contributors can read the lesson as the draft progresses. 

_If we have not received the Submission package by April_, @jrladd will attempt to contact @Dr-Hutchinson. If we do not receive any update, this Issue will be closed. 

Our dedicated Ombudspersons are [Ian Milligan (English)](mailto:i2milligan@uwaterloo.ca), [Silvia Gutiérrez De la Torre (español)](mailto:silviaegt@gmail.com), [Hélène Huet (français)](mailto:hhuet@ufl.edu), and [Luis Ferla (português)](mailto:ferla@unifesp.br) Please feel free to contact them at any time if you have concerns that you would like addressed by an impartial observer. Contacting the ombudspersons will have no impact on the outcome of any peer review.

**Comment by jrladd** [comment] 2024-03-20 19:08
Daniel (@Dr-Hutchinson), I just wanted to say hello and that I'm looking forward to working with you on this lesson! At this first stage of the process, we'll work mostly by email. I'm looking forward to reading your draft when it's ready—in the meantime please let me know if there's anything you need as you prepare the lesson.

**Comment by jrladd** [comment] 2024-07-08 17:58
A quick update: I've received a draft of this lesson from @Dr-Hutchinson, and I'm going to get start my initial readthrough and begin reaching out to potential peer reviewers.

**Comment by jrladd** [comment] 2024-08-12 16:43
The updated draft from @Dr-Hutchinson is attached, and all the files and assets are in [this repo](https://github.com/Dr-Hutchinson/programming_historian/tree/main). @anisa-hawes, these are ready to be checked and added to the submissions repo, but/and I know this coincides with the August break. In the meantime I am working on reviewers for the lesson—I received one informal yes from someone at the DH conference last week, and I have some other leads.

[hutchinson_draft_2.md](https://github.com/user-attachments/files/16589622/hutchinson_draft_2.md)

**Comment by anisa-hawes** [comment] 2024-09-04 12:44
Thank you for sharing these submission materials, Daniel @Dr-Hutchinson and @jrladd.

@charlottejmc and I will process the files and get the lesson preview set up for you this week!

**Comment by charlottejmc** [comment] 2024-09-06 03:24
Hello @Dr-Hutchinson and @jrladd,

You can find the key files here:
- .md: [/en/drafts/originals/exploring-text-collections-via-rag.md](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/en/drafts/originals/exploring-text-collections-via-rag.md)
- images: [/images/exploring-text-collections-via-rag](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/exploring-text-collections-via-rag)
- assets: [/assets/exploring-text-collections-via-rag](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/assets/exploring-text-collections-via-rag)

You can review a preview of the lesson here: 
- <http://programminghistorian.github.io/ph-submissions/en/drafts/originals/exploring-text-collections-via-rag>

------

Hello @Dr-Hutchinson, as you can see, I've created a dedicated Image folder and Assets folder on our ph-submissions GitHub repo, to host the files needed for your lesson. I had a few queries while processing these files, however, and would appreciate your help to solve them. I've outlined them below  (I've renamed the images according to our Image Naming Convention, but I'll use your original names below for clarity):
- [ ] I noticed that you embedded [Open_Rag_Diagram_1.png](https://github.com/Dr-Hutchinson/programming_historian/blob/main/media/Open%20Rag%20Diagram_1.png) twice in the lesson, as 'Figure 2'. I wonder whether it might be sufficient and simpler to only include it once, especially in consideration of site lightness. 
- [ ] You haven't used [Open_Diagram.png](https://github.com/Dr-Hutchinson/programming_historian/blob/main/media/Open%20RAG%20Diagram.png) in the lesson, so I did not include it in the image folder. Is that correct?
- [ ] You'll notice that the assets folder is currently empty – I was hoping for your input before creating it. Essentially, we want to host all the files which will be necessary (or helpful) for readers when following the lesson. Could you help me to pick these out? Here is what I was able to find in the lesson body so far:
- https://github.com/Dr-Hutchinson/nicolay/blob/main/data/individual_speeches_and_metadata/Text%20%23_%2072.txt
- https://github.com/Dr-Hutchinson/nicolay/blob/main/data/individual_speeches_and_metadata/Text%20%23_%2058.txt
- https://github.com/Dr-Hutchinson/nicolay/blob/main/data/individual_speeches_and_metadata/Text%20%23_%2066.txt
- https://github.com/Dr-Hutchinson/nicolay/blob/main/data/lincoln_speech_corpus.json 
- https://github.com/Dr-Hutchinson/nicolay/blob/main/data/lincoln_speech_corpus.json
- https://github.com/Dr-Hutchinson/programming_historian/blob/main/prompts/metadata_generation_prompt.txt
- https://github.com/Dr-Hutchinson/programming_historian/blob/main/Hutchinson_draft_1.ipynb
- https://github.com/Dr-Hutchinson/programming_historian/tree/main/evaluation/relevance_task
- https://github.com/Dr-Hutchinson/programming_historian/blob/main/Hutchinson_draft_1.ipynb
- https://github.com/Dr-Hutchinson/nicolay/tree/main/data/finetuning_datasets

Some of these link to the `nicolay` repo, while others link to the `programming_historian` repo you shared with us. 
- [ ] I see that you've created an `.ipynb` version of the lesson for readers to use in Google Colab (for example). When authors provide notebooks associated with their lesson, we want them to be hosted within our infrastructure (i.e. in the assets folder) so that we can manage them and ensure their sustainability.

To support this, we’ve developed some guidelines for authors who choose to integrate notebooks in their lessons. Our aim is to ensure effective maintenance, future translatability, and flexible usability.

These guidelines are based on a key understanding that we want our readers to be able to make the choice to work either in Google Colab, in their preferred alternative cloud-based development environment, or opt to run the code locally.

If authors provide notebooks to accompany their lesson, we ask that:

- Notebooks consist of the code + line comments only
- Headings and subheadings mirror those of the lesson, to support readers' navigation
- Notebooks do not replicate nor extend commentary from the lesson

Currently, it appears that [Hutchinson_draft_1.ipynb](https://github.com/Dr-Hutchinson/programming_historian/blob/main/Hutchinson_draft_1.ipynb) replicates the lesson text, as well as includes additional code which is not found in the lesson (judging from the sentence "Full code for how these evaluations were measured can be found [here](https://github.com/Dr-Hutchinson/programming_historian/blob/main/Hutchinson_draft_1.ipynb)." (Line 2434). It might be better for this additional code to be supplied in a simple stand-alone file instead, and to pare down the notebook so that it contains only section headings and the code blocks which appear in the lesson body.
- [ ] Finally, I'd like to ask whether you could provide slightly more descriptive alt-text for the figures. This element enables screen readers to read the information conveyed in the images for people with visual impairments, different learning abilities, or who cannot otherwise view them, for example due to a slow internet connection. **It's important to say that 'alt-text' should go further than repeating the figure captions.**

We have found [Amy Cesal's guide to Writing Alt Text for Data Visualization](https://medium.com/nightingale/writing-alt-text-for-data-visualization-2a218ef43f81) useful. This guide advises that alt-text for graphs and data visualisations should consist of the following:

`alt="[Chart type] of [data type] where [reason for including chart]"` 

What Amy Cesal's guide achieves is prompting an author to reflect on their _reasons_ for including the graph or visualisation. What idea does this support? What can a reader learn or understand from this visual?

[The Graphs section of Diagram Center's guidance](http://diagramcenter.org/specific-guidelines-e.html) is also useful. Some key points (relevant to all graph types) we can take away from it are:

- Briefly describe the graph and give a summary if one is immediately apparent
- Provide any titles and axis labels 
- It is not necessary to describe the visual attributes of the graph (colour, shading, line-style etc.) unless there is an explicit need
- Often, data shown in a graph can be converted into accessible tables

For general images, [Harvard's guidance](https://accessibility.huit.harvard.edu/describe-content-images) notes some useful ideas. A key point is to keep descriptions simple, and adapt them to the context and purpose for which the image is being included.

Would you feel comfortable making a first draft of the alt-text for each of the figures? This is certainly a bit time-consuming, but we believe it is very worthwhile in terms of making your lesson accessible to the broadest possible audience. We would be very grateful for your support with this.

----
Thank you very much for your patience and your energy! 

If you have any further questions, @anisa-hawes and I are here to help, so please do reach out here in the comments.

**Comment by Dr-Hutchinson** [comment] 2024-09-09 19:45
Greetings,

I wanted to offer my belated thanks for your careful review and feedback of
my lesson for the Programming Historian. I just wanted to reach out and
confirm my receipt of this message, and share that I'm at work on
implementing these revisions, which I hope to complete by next Friday. I
will reach out with questions as they arise; in the meantime, my thanks
again for everything. The preview looks great, and I'm excited to see this
project progress to the finish line.

Thanks again,

Daniel

**Comment by anisa-hawes** [comment] 2024-09-11 10:07
Thank you, Daniel @Dr-Hutchinson. We're excited about your lesson too! 

@charlottejmc and I are very happy to collaborate with you to resolve these initial queries raised during file processing. When you've worked through the adjustments required, we'll hand over to @jrladd who will do a full read of the draft and help us move it towards the next phase.

**Comment by jrladd** [comment] 2024-09-16 20:31
Hey @Dr-Hutchinson @anisa-hawes @charlottejmc, thanks so much for all of these updates! I've done my full read-through already and those revisions are in place (we took a slightly different path getting to this stage). So I will look this over once more now that it's up, but we're ready for external reviewers. I'm waiting to hear back from one more reviewer, and when I do I will update everyone with the next steps!

**Comment by charlottejmc** [comment] 2024-09-18 05:26
Hi @jrladd, I'm not sure I fully understand your message! 

I currently don't see any new commits to the lesson files – if you and @Dr-Hutchinson have implemented the revisions I brought up in [my initial comment](https://github.com/programminghistorian/ph-submissions/issues/611#issuecomment-2333163236), would you be able to point to where those can now be found? It would be great if you could also tick them off as you go through them.

Thanks so much 😊

**Comment by anisa-hawes** [comment] 2024-09-18 10:02
Thank you for the work you've already done to process these lesson materials, @charlottejmc. 

Hello Daniel @Dr-Hutchinson,
I'd like to ask for your help to resolve the queries that @charlottejmc sets out in [her comment above](https://github.com/programminghistorian/ph-submissions/issues/611#issuecomment-2333163236). We'd be grateful if you could check off the tasks/questions as you work through them. We're happy to be in touch if any points are not clear, and to offer support where we can - just let us know. If it is easier, feel free to contact Charlotte by email: publishing.assistant[@]programminghistorian.org.

Thank you, @jrladd. We'll write you a note here to confirm when our work on the submission is complete and we're ready to hand it over for your read in Phase 2 Initial Edit ☺️

**Comment by jrladd** [comment] 2024-09-18 21:44
Hi @charlottejmc @anisa-hawes, my apologies for causing confusion! My message was poorly worded. I only meant to say that some of the work typically done as part of the Phase 2 initial edit has already been done, and that once @Dr-Hutchinson addresses the changes you both suggested we'll be ready to move ahead. 

Daniel, please go ahead and work on those revisions as you've already planned to do, and I'll have things ready to go once those are in place. Thanks so much for your work on this, everyone!

**Comment by Dr-Hutchinson** [comment] 2024-09-24 02:25
My apologies for the slow turnaround, but happy to share my edits and responses to @charlottejmc's helpful feedback for my lesson for the Programming Historian. Below I address them in turn as they appear in the original feedback:

- **Open_Rag_Diagram_1.png**: Please feel free to only use this image once, as currently laid out in the "Developing a RAG App: Things to Consider" section.
- **Open_Diagram.png**: Yes, feel free to exclude this image from the folder
- **Assets Folder**: I can confirm the inclusion of the following files for this folder:
  - [Text #72](https://github.com/Dr-Hutchinson/nicolay/blob/main/data/individual_speeches_and_metadata/Text%20%23_%2072.txt)
  - [Text #58](https://github.com/Dr-Hutchinson/nicolay/blob/main/data/individual_speeches_and_metadata/Text%20%23_%2058.txt)
  - [Text #66](https://github.com/Dr-Hutchinson/nicolay/blob/main/data/individual_speeches_and_metadata/Text%20%23_%2066.txt)
  - [Lincoln Speech Corpus](https://github.com/Dr-Hutchinson/nicolay/blob/main/data/lincoln_speech_corpus.json)
  - [Metadata Generation Prompt](https://github.com/Dr-Hutchinson/programming_historian/blob/main/prompts/metadata_generation_prompt.txt)

  The following links are mentioned in the lesson, which are directory paths containing multiple files, none which are directly related to the lesson but just for reference for additional research. They wouldn't need to be in the assets folder.
  - [Relevance Task](https://github.com/Dr-Hutchinson/programming_historian/tree/main/evaluation/relevance_task)
  - [Finetuning Datasets](https://github.com/Dr-Hutchinson/nicolay/tree/main/data/finetuning_datasets)

  In addition, the following file could be included in the assets folder:
  - [2-Shot RAG Prompt](https://raw.githubusercontent.com/Dr-Hutchinson/programming_historian/main/prompts/2_shot_RAG_prompt.txt)

  I can also confirm the removal of this file:
  - [Original Notebook](https://github.com/Dr-Hutchinson/programming_historian/blob/main/Hutchinson_draft_1.ipynb)

- **Google Colab**: Per your request, I've formatted a new Google Colab notebook with narrative elements removed and headings matching the article. The URL for the new file is:
  - [Updated Colab](https://github.com/Dr-Hutchinson/programming_historian/blob/main/Hutchinson_draft_2.ipynb)

  I'm happy to remove the original Colab from my GitHub at your direction. Please feel free to reach out if additional edits are needed.

- **Alt-text captions**: Thank you for the helpful feedback on developing better alt-text captions. Those have been added in a fork of the lesson draft. I'm happy to edit further as needed.

I have made the requested changes and created a pull request for your review:

- Updated alt-text captions
- Revised notebook as per your guidelines
- Removed duplicate images and adjusted the assets folder

You can view the pull request here: [#627](https://github.com/programminghistorian/ph-submissions/pull/627).

Please let me know if you need further adjustments. Thanks very much everyone for the assistance and feedback!

**Comment by anisa-hawes** [comment] 2024-09-24 21:10
Many thanks, Daniel @Dr-Hutchinson! 

I've merged in PR #627 to commit your changes. This week, Charlotte will be able to work through the notes you shared above to process the asset files, and review the alt-text you've prepared. 

I'd like to take this opportunity to raise a couple of 'formatting' issues which I wonder if you could consider adjusting before we move onwards:

Firstly, I think it would be worth re-thinking the use of tables. In particular, I find Tables 2, 3, and 4, difficult to read. A combination of factors are at play (including idiosyncrasies of our Markdown stylesheets) but, at the moment, the longer-form texts are challenging to parse because the narrow column width creates too-frequent line breaks < [preview](https://programminghistorian.github.io/ph-submissions/en/drafts/originals/exploring-text-collections-via-rag) > Could we consider experimenting with a different way of presenting these keyword search results? Could a series of boxes (like those you make use of in the Introduction) containing carefully organised paragraphs present the same information? Do the sample keyword search results need to be as long? (or could they be truncated?). These aspects can be tricky, so please let me know if you'd like Charlotte and I to help you experiment with some alternative options.

Secondly, a more fundamental point, is that I notice you've included several extended blocks of code (in particular, between paragraphs 52-55 and 71-74 as numbered in the current preview). Although I notice you make use of inline comments, I suspect these blocks may still be challenging for readers to make sense of. We encourage authors to break their code down, and talk their reader through action-by-action, explaining how it is constructed, and what functions are performed. My suggestion would be to begin by extracting the inline comments you've already written, then expanding these into sentences or short paragraphs which highlight the functions performing those key tasks, and the decisions being made by the programmer. As I said, this is essentially a formatting adjustment but I think breaking the code into blocks of meaning, building in explanation and reflection will also serve to ensure that your reviewers (and future readers) will be able to get the best from this lesson as a learning resource. Do you think this is something you could work on adjusting?

Best, Anisa

**Comment by charlottejmc** [comment] 2024-09-26 03:17
Hello @Dr-Hutchinson,

Thank you very much for working on the queries I had set out for you.

I am particularly impressed with your improved alt-text, which is exactly what we were looking for. I saw that you have renamed your lesson "Data, Dialogue, and AI: Exploring Text Collections with Large Language Models via Retrieval Augmented Generation", so I have updated the issue name to reflect that.

---

I have created your lesson's dedicate [assets folder](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/assets/exploring-text-collections-via-rag) where I have saved the necessary files. 

Please take the time to review [this commit](https://github.com/programminghistorian/ph-submissions/commit/7d9f1ec757e0c111de604c25ba64a359b92b8953), to check whether my changes have not affected your code in any way. There may be some complications at lines 144 and 2165.

---

Thank you for working on the new version of the notebook. I think we're nearly there, but it still needs a little bit of work. 

- I have cleared the outputs, as we don't need to include them for the readers. Hopefully, they will be able to generate them using the code themselves!
- On this note, I'm not sure you need to include the code output in your lesson either, except where absolutely relevant.
- I have reformatted the headings using Markdown cells, making it easier for readers to navigate through the sections
- I can't find the last 8 cells in your lesson, so they shouldn't really be included in the notebook. Please remember, the notebook should only be a mirror of your lesson's headings and code blocks. If these 8 cells consist of additional, optional code, let's structure them into a separate script or notebook, which we can link to directly where relevant.

---
An additional point to Anisa's comment above about the code block formatting: in our lessons, we use three backticks above and three backticks below the code blocks (and only single backticks around short in-line code). 
- I have made these changes to your lesson code
- I have replaced your numbered subheadings with hashed out in-line comments
- Where these subheadings indicated an output, I have preceded the code block with 'Output:' written in the text body instead.
- You can review these changes in [this commit](https://github.com/programminghistorian/ph-submissions/commit/11bdef56371c07f0abc5b079fa4aeeefbfdbc2a0)

Thank you for your patience and energy as we work through this!

**Comment by Dr-Hutchinson** [comment] 2024-09-26 17:47
Hello @anisa-hawes and  @charlottejmc,

Thanks very much for the continued review and improvements. Happy to share some progress. 

 Concerning @anisa-hawes 's comments:

- No problem on reformatting the tables. I've edited table 2 to truncate it and format it like the first text table at the start of the lesson. If the formatting looks acceptable, I'll reformat the tables 3 and 4 accordingly.
- Thank you for the feedback concerning revising the code blocks. I definitely want to ensure accessibility and readability, so your advice is much appreciated. I've reformatted the code blocks for sections 39-55 to break down the code and make it more modular and readable. I'm happy to provide more explanation and granularity as needed; let me know what you think and I can revise further or proceed to the other code blocks you've identified.  

Concerning @charlottejmc 's comments:

- Thanks for reformatting the headers and clearing the outputs in the notebook. I agree concerning clearing the outputs in the lesson, and I'll revise accordingly.
- Apologies for the last 8 cells in the revised notebook. This code was used to create the graphs, and these cells can be deleted from the notebook.

Thanks for your patience, and based on your feedback I'll move forward to complete the remaining formatting edits.

**Comment by anisa-hawes** [comment] 2024-09-27 08:46
Hello Daniel @Dr-Hutchinson,

To reiterate, we rather that authors don't use the PR system in the ph-submissions repository. 

With the invitation I've sent you, you already have 'write access' so you can simply edit your lesson directly: [/en/drafts/originals/exploring-text-collections-via-rag.md](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/en/drafts/originals/exploring-text-collections-via-rag.md). No patches or forks are required.

Thank you,
Anisa

**Comment by hawc2** [comment] 2024-10-04 14:45
Hi @Dr-Hutchinson, just chiming in after looking over your current draft. This draft is way over length - the word limit for a PH lesson is 8000 words including code, and this is 3 times as long. 

I would encourage you to review the PH lessons that we have published to get more of a sense of the style and length we are looking for. It's possible this lesson could be broken into two parts, but we really want to avoid doing that unless necessary, and in this case, your lesson is still much too long. 

Besides the problem of overall length, the code chunks are also so long they could be full scripts unto themselves. If you look at PH lessons we've published in the past, you'll see ideally the code chunks are short and instead of in-line comments, you use commentary in the paragraph writing of the lesson to explain what the code does. 

I'm concerned how long this lesson has taken to progress, and considering how much work it needs, I think it would be best for you to revise this lesson and resubmit it for our next call for lessons, which will be going out in the next few weeks. As long as you can address these concerns, we would be happy to prioritize your lesson for consideration for publication in 2024. I hope that works?

**Comment by Dr-Hutchinson** [comment] 2024-10-04 15:50
Greetings @hawc2,

First, I want to offer my thanks to you and the other team members for the review and feedback on this article. Given your concerns, I agree that further revision is needed and I appreciate the opportunity to revise and resubmit for the next call for lessons. I do have some ideas about making the lesson both more concise and streamlined in terms of the code. I've gone ahead and submitted my edits responding to @anisa-hawes's helpful feedback, but I understand more substantial revisions (and reductions) are needed. I will get those underway. When the next call for lessons is issued please share with me the process for resubmission, and I look forward to sharing my progress. Thanks again.

**Comment by anisa-hawes** [comment] 2024-10-04 15:57
Thank you for your swift response, Daniel @Dr-Hutchinson. We really appreciate the energy you have given during this initial phase.

I'll make a note to write to you directly (I have your email contact) when our EN call for proposals is open so that you can re-submit - we look forward to that.

Thanks also to @jrladd and @charlottejmc.


---

I've moved the Markdown file to: [/en/drafts/originals/inactive/exploring-text-collections-via-rag.md](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/en/drafts/originals/inactive/exploring-text-collections-via-rag.md).

**Closed as completed by anisa-hawes** 2024-10-04 15:57 UTC
Labels: English, 1. Submission, Original
