### ISSUE TITLE
Traducción: Visión artificial para las humanidades: Una introducción al aprendizaje profundo para la clasificación de imágenes (Parte 1)

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/ph-submissions#557] opened 2023-04-21 20:06 UTC
The _Programming Historian en español_ has received the proposal for the translation of lesson 'Computer Vision for the Humanities: An Introduction to Deep Learning for Image Classification (Part 1)' by Diana Cifuentes @dcanalitica
 	
In order to promote speedy publication of this important topic, we have agreed to a submission date of no later than **end of June**. The author(s) agree to contact the editor in advance if they need to revise the deadline.
 
If the lesson is not submitted by ~June 30th~ **July 15th**, the editor will attempt to contact the author(s). If they do not receive an update, this ticket will be closed. The ticket can be reopened at a future date at the request of the author(s).
 
The main editorial contact for this lesson is, for now, @jenniferisasi.

Vista previa

http://programminghistorian.github.io/ph-submissions/es/borradores/traducciones/vision-artificial-para-humanidades-pt1

**Comment by jenniferisasi** [comment] 2023-07-17 16:59
He recibido el documento markdown con la traducción por parte de Diana. Estos días haré una primera lectura y dejaré mis comentarios.

**Comment by anisa-hawes** [comment] 2023-07-20 18:48
¡Hola! @jenniferisasi 

The key files are here:

- .md file: [/es/borradores/traducciones/vision-artificial-para-humanidades-pt1.md](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/borradores/traducciones/vision-artificial-para-humanidades-pt1.md)
- images: [/images/computer-vision-deep-learning-pt1](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/computer-vision-deep-learning-pt1)
- assets: [/assets/vision-artificial-para-humanidades-pt1-2](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/assets/vision-artificial-para-humanidades-pt1-2/vision-artificial-para-humanidades-pt1-2.ipynb)

You can read a preview of the submission here: 

Preview: http://programminghistorian.github.io/ph-submissions/es/borradores/traducciones/vision-artificial-para-humanidades-pt1

As I mentioned when we chatted earlier today, several of the images will definitely need to be created anew because they contain English text. If the translator doesn't have capacity to do this, I could collaborate with you to recreate these.

We'll also need alt-text to accompany each figure image. I've slotted in some placeholder text for now.

**Comment by jenniferisasi** [comment] 2023-07-20 18:57
Wonderful, thanks so much for working on this @anisa-hawes! I will now proceed to read it and see if we can move it on or if it needs anything before reviews.

**Comment by anisa-hawes** [comment] 2023-07-27 12:14
Hola @jenniferisasi and @dcanalitica,

I've sent you an email to share a Powerpoint document created by our colleagues on the FR team (💞) which contains templates for translating the diagram figures 5, 6 and 7 of this lesson. 

If you'd like to email me your new versions of these three images, I can take care of re-sizing, renaming and uploading them to the right directory so that the Preview of this submission displays correctly. 

Let me know if you have any questions. Anisa

**Comment by jenniferisasi** [comment] 2023-09-07 20:02
Mensaje enviado a la traductora, quien se compromete a enviarnos una versión revisada en aproximadamente un mes a partir del 11 de septiembre

**Comment by jenniferisasi** [comment] 2023-11-22 16:38
¡Traducción revisada recibida! La lea tan pronto como me sea posible para que entre en la línea de edición. Gracias por tu paciencia @dcanalitica

**Comment by jenniferisasi** [comment] 2023-11-29 02:31
Salvo por un par de cambios rápidos, la traducción puede pasar a fase de edición y revisión, aunque faltaría traducir las instrucciones dentro de los cuadros de código de Python, por ejemplo (abajo) así como traducir las imágenes que pueden ser adaptadas (enviadas por email por @anisa-hawes)

```
ad_data = ImageDataLoaders.from_csv(
    path="ads_data/", # root path to csv file and image directory
    csv_fname="ads_upsampled.csv/", # the name of our csv file
  ...
```

@anisa-hawes shall I send you the .md file with the updated text? I need to adapt the YAML but other than that it should work. Thanks!

Voy a consultar con el equipo para buscar editor disponible.

**Comment by anisa-hawes** [comment] 2023-11-30 14:55
Thank you, @jenniferisasi. Yes! Please do. 

We can take care of any necessary adjustments to the YAML – that's no problem. 🙂

**Comment by dcanalitica** [comment] 2023-12-28 17:38
Hola Jennifer,
Recibí los correos pero realmente no sé que debo hacer.
Gracias.
un saludo,

Diana Cifuentes

**Comment by anisa-hawes** [comment] 2024-01-03 14:40
Hola @dcanalitica,

Happy New Year! Thank you for your message and apologies for the delay in replying to you.

@jenniferisasi shared your revised markdown file with me. I've applied your edits, https://github.com/programminghistorian/ph-submissions/commit/f4d41e2e4587b7689eaa2b12a34ea90db5fe0b40, while preserving the YAML header, our liquid syntax (to display and caption images), and our endnote syntax. 

The Powerpoint document I shared with you by email contains "mute" versions of the diagrams for figures 5, 6 and 7. The labels and annotations on these diagrams need to be translated into Spanish. One of our French team translators kindly shared these template diagrams with us, realising how useful they could be to other teams :-). You can either edit the Powerpoint slides directly and email them to us, or simply email us the plain text in Spanish to apply on your behalf – whatever is easiest for you. We are happy to take care of creating the images, re-sizing, renaming and uploading them to the right directory. 

As @jenniferisasi [mentions in her comment above](https://github.com/programminghistorian/ph-submissions/issues/557#issuecomment-1831115371) we also need to translate any explanatory notes (which start with a `#`) inside the code blocks . Are you comfortable working on the file directly to do this? [/es/borradores/traducciones/vision-artificial-para-humanidades-pt1.md](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/borradores/traducciones/vision-artificial-para-humanidades-pt1.md). Please let me know if you have any questions, or if you would prefer us to send us the line edits here as a comment, or by email. **It's easier for us if we all work on this version only from now on. Going back to your original draft to make edits makes things more fiddly, because we need to preserve our liquid syntax + endnotes + YAML which are all in place**.

One last note, is that I've updated the filename + lesson slug, to include the suffix `-pt1`: `vision-artificial-para-humanidades-pt1`. (I've updated the links above to the file and the Preview).

**Comment by anisa-hawes** [comment] 2024-05-17 11:26
Hola Diana @dcanalitica and @jenniferisasi,

We are in the process of coordinating a migration of the codebook linked to this lesson from Kaggle to Colab. With support from the authors of the original lesson, we are also adjusting the codebook so that it consists of the code + essential line comments only, headings and subheadings that mirror the lesson, and does not extend or replicate commentary. (There is one codebook which is linked to both parts of the lesson).

We are now working on a first draft of revisions to the original EN lesson in [Issue #3266](https://github.com/programminghistorian/jekyll/issues/3266) so that the sections and sentences that refer to the specifics of working with Kaggle are removed. We will be collaborating with Alex Wermer-Colan (Managing Editor of our English journal) on these updates to the original lesson.

When revisions to the original lesson are finalised, we would like to support you to revise the translations as well. We'll create a new copy of the codebook in Colab so that you can translate the section headings + line comments. I'll write a comment here to update you when the revisions are complete.

Thank you for your patience,
Anisa

**Comment by dcanalitica** [comment] 2024-05-24 17:21
Ok, perfect.
Should I need to do something?
Thank you
Diana Cifuentes

**Comment by anisa-hawes** [comment] 2024-05-24 18:17
Hello @dcanalitica.

Thank you for your message. No, there is nothing you need to do yet. 

We'll update you here when revisions to the original are confirmed. ☺️ 

We appreciate your patience.

**Comment by anisa-hawes** [comment] 2024-07-05 19:11
Hello Diana @dcanalitica and @jenniferisasi,

With the support of the original authors, we have now migrated this lesson's codebook from Kaggle so that we can manage it directly here in our GitHub repository. 

I've created a copy of this for your translation [vision-artificial-para-humanidades-pt1-2.ipynb](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/assets/vision-artificial-para-humanidades-pt1-2/vision-artificial-para-humanidades-pt1-2.ipynb), which you can edit directly to translate the headings, subheadings and author notes from English to español. I apologise for the delay in preparing this for you.

We are very much still trialling and refining our workflows for handling codebooks, so we would appreciate your feedback about which ways of working on the codebook translation you feel is most practical. 

We're here if you have questions.
Thank you.

**Comment by anisa-hawes** [comment] 2024-10-31 16:33
Hello Diana @dcanalitica,

I hope you're well?

Do you have capacity to return to working on this translation? 

Please let us know. If we don't hear from you within ~2 weeks, we will close this Issue. If you decide to return to this in the future, we can reopen the Issue - none of the work you've done so far will be lost.

With thanks,
Anisa

**Comment by anisa-hawes** [comment] 2024-12-05 15:34
Hello Diana @dcanalitica,

We are closing this Issue due to inactivity. Please write to our Managing Editor @jenniferisasi if you decide that you'd like to return to work on this translation in 2025.

With our thanks,
Anisa

**Closed as completed by anisa-hawes** 2024-12-05 15:34 UTC
Labels: Translation, Español, 3. First Revision
