### ISSUE TITLE
Review Ticket: Introduction to Geospatial Percent Change Analysis Using R and RStudio

### ISSUE THREAD

**Issue by ZoeLeBlanc** [programminghistorian/ph-submissions#260] opened 2019-09-18 19:45 UTC
The Programming Historian has received the following tutorial on 'Introduction to Geospatial Percent Change Analysis Using R and RStudio' by @criopelle and Jorge Quintela Fernandez. This lesson is now under review and can be read at:

http://programminghistorian.github.io/ph-submissions/lessons/geospatial-percent-change-r

Please feel free to use the line numbers provided on the preview if that helps with anchoring your comments, although you can structure your review as you see fit.

I will act as editor for the review process. My role is to solicit two reviews from the community and to manage the discussions, which should be held here on this forum. 

Members of the wider community are also invited to offer constructive feedback which should post to this message thread, but they are asked to first read our Reviewer Guidelines (http://programminghistorian.org/reviewer-guidelines) and to adhere to our anti-harassment policy (below). We ask that all reviews stop after the second formal review has been submitted so that the author can focus on any revisions. I will make an announcement on this thread when that has occurred.

I will endeavor to keep the conversation open here on Github. If anyone feels the need to discuss anything privately, you are welcome to email me. You can always turn to @amandavisconti if you feel there's a need for an ombudsperson to step in.

## Anti-Harassment Policy

This is a statement of the Programming Historian's principles and sets expectations for the tone and style of all correspondence between reviewers, authors, editors, and contributors to our public forums.

> The Programming Historian is dedicated to providing an open scholarly environment that offers community participants the freedom to thoroughly scrutinize ideas, to ask questions, make suggestions, or to requests for clarification, but also provides a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. We do not tolerate harassment or ad hominem attacks of community participants in any form. Participants violating these rules may be expelled from the community at the discretion of the editorial board. If anyone witnesses or feels they have been the victim of the above described activity, please contact our Ombudsperson (@amandavisconti). Thank you for helping us to create a safe space.

**Comment by ZoeLeBlanc** [comment] 2019-09-18 19:56
Thanks @criopelle for this submission!
I will be reading the lesson over the next week and providing some feedback for you to respond to, and then I will solicit formal reviewers. 

Two quick requests:
1. Would it be possible to get Jorge's Github handle to tag him here as well?
2. I've fixed some formatting issues, but one outstanding issue is that you list endnotes at the end of the lesson but use formatting that only renders for footnotes. Could you either change those endnotes to numbered references or to footnotes (totally your preference)?

Also please let me know if you have any questions about the process.

**Comment by criopelle** [comment] 2019-09-24 15:36
Hello Zoe,

Thank you for your questions, and for reading the lesson—to address your questions:


1)      Jorge’s Github handle is jaquintela

2)      Could you clarify (or point me to a resource that clarifies) how to format the references/footnotes properly?

Thank you,

Cameron

**Comment by ZoeLeBlanc** [comment] 2019-10-21 00:42
Hi @criopelle and @jaquintela! Apologies for my delay, but I had a serious family emergency that needed my attention. I've now gone through your lesson and pushed my changes up to a separate branch so that you would be able to approve them. You can see the changes listed #266 and please let me know if you have any questions about them or feel strongly about any of the changes. I ended up just changing the endnotes to numbered list since the issue we were having was with how Github renders Markdown, and not an issue specific to the Programming Historian guidelines.

I would also recommend the following changes to the lesson: 
- [ ] P 11 you mention "small area estimation methods." Could you elaborate what this means or include a link?
- [ ] P 12 you use “c:\temp\City_Miami” but that is not where downloads are located on Macs. We don't have a standardized approach for file downloads, but I would recommend including instructions for the reader to create a folder, find the data in their downloads folder, and then moving the data to this new folder
- [ ] P 15 repeats the same information in P 12, maybe combine the two paragraphs into P 12 especially since you mention the downloads location in P 15
- [ ] P 19 change setwd command to be the new folder that the reader created rather than the path that is used on Windows machine (also be sure to do this for all later mentions of the data path)

Once you've had a chance to go over the rest of my changes and then added these ones as well, I'll start soliciting reviewers for the lesson. Please let me know if you have any questions about my suggestions or changes, and thank you for your patience.

**Comment by criopelle** [comment] 2019-11-13 14:52
Hello Zoe,

Good morning! We have accepted your suggestions and made the following changes on our article for the Programming Historian:

1. Accepted formatting changes from Zoe LeBlanc
2. Added link to CDC small area estimation methods in paragraph 11
3. Paragraph 12 vs Paragraph 15: we merged the content into Paragraph 12 and changed Paragraph 15 into a reminder to double check the prevous section instead.
4. Setting the working directory: Setwd() lack of clarity for Windows vs. Mac: we fixed the code with illustrations of how to setwd() properly with Windows Vs. Mac.
5. Added additional instructions for Windows vs. Mac users for lines 172/173 which is an import data step

Please let us know if there are any additional comments or changes you might have for us before sending it out for review--we really appreciate all your work on editing and reviewing our submission. If you can confirm that you've received these changes and where we are in the process, we would greatly appreciate it.

Thank you,

Cameron



---------------------

Cameron Riopelle, Ph.D.

Head of Data Services

University of Miami Libraries

1300 Memorial Drive
Coral Gables, FL 33146

criopelle@miami.edu<mailto:criopelle@miami.edu>



Appointments available via Outlook (for UM employees) or at https://criopelle.youcanbook.me/

________________________________

**Comment by criopelle** [comment] 2019-11-22 15:03
Hi Zoe,

I'm just following up to make sure our changes have been received.

Thank you,

Cameron

**Comment by ZoeLeBlanc** [comment] 2019-11-27 15:35
Thanks @criopelle and @jaquintela for the changes to the lesson! 

I've merged everything in and now am soliciting reviewers. If there's anyone you have in mind that might have expertise in either R or geospatial analysis, please feel free to recommend them. Otherwise I'll update you once I have confirmations from two reviewers (hopefully in the next two weeks or so!).

**Comment by svmelton** [comment] 2019-12-31 00:00
Hi @ZoeLeBlanc—just checking in. Have you been able to identify reviewers? Do you need any help?

**Comment by ZoeLeBlanc** [comment] 2020-01-06 17:34
@svmelton thanks for checking. So far I have one but struggling to find another person. Any suggestions would be very much appreciated 🙏

**Comment by ZoeLeBlanc** [comment] 2020-01-17 17:12
@bmschmidt and @hepplerj
 have agreed to serve as our lesson reviewers 🎉 . They've agreed to a submission date for their reviews of March 20, 2020.

Just a reminder reviewer guidelines can be found here https://programminghistorian.org/en/reviewer-guidelines, and that we're following an open review process. All reviews should be posted in this ticket thread and feel free to look at previous submission tickets for examples. Also please post here or email me any questions you have about the process.

This ticket will be open to any other feedback from our community while we wait for our reviewers to submit. Once we have received both reviewers' responses, the open review period will then be closed. I will summarize the feedback from both reviewers as well as any other input from our community, and work with @criopelle and @jaquintela to decide what further editing the lesson will need.

Please do not make any edits to the lesson draft @criopelle and @jaquintela until we've received both reviews and I've written up my summary - that way I have a chance to prioritize comments and work out any conflicting advice.

Thanks to our reviewers and looking forward to working together 😊

**Comment by bmschmidt** [comment] 2020-01-17 18:02
I'm always sort of confused by how to assess these PH pieces that are like "here's how to do x and y using tools d and e". This piece does clearly spell out its goals, and delivers a way to do so. I'm confident it could be brought up to PH standards, although it would take some work.

But as I told the editors, I don't think I have time to participate in the review process beyond the comments below because I think it would take quite a bit to make this something I would be willing to refer students to. I know "Ben would tell his history MA students to use it" isn't a reviewing criteria, so I feel a little bad for deploying it. But I don't know what else is the ultimate purpose of things published here.

But the questions I always ask of something like this are:

1. **Soundness** Does this provide a *sound* way to do this task? Does the code show an understanding of the language.
2. **generalizability** Does it provide enough information that people will know how to do their *own* tasks? (ie., is it different from a blog post?)
3. Are there resources to teach this already available?

This submission needs substantial work on all three.

## soundness

Two problems here. In this case, I can't really see why anyone would do the particular set of tasks here in R rather than in ArcGIS or QGIS if they're not already familiar with R. Certainly, the first step needs to be thinking about the right tool for the job. Since there's almost no computation in this map and immense work spent on styling in the code, I think Arc would be the way to go.

Additionally, If I were going to do this chart  and if someone wants to learn to work w/ geospatial data in R, they should probably be doing that either because they know some of the old statistics routines--in which case, probably not a PH reader--or because they're learning to do it in the context of general tidyverse plotting. In that case I would tell them to use `sf` and `ggplot`, not `Rgdal` and `tmap`. `tmap` is certainly nice--and it's even used by an existing PH tutorial. [https://programminghistorian.org/en/lessons/geospatial-data-analysis]. But that one, at least, uses `sf` which is a much clearer and more modern way of doing geospatial work in R. And Rgdal's methods for interfacing with spatial data frames feel obsolete to me now that I've generally switched to `sf`, especially for teaching.

There's also a lot of weirdness in the code here that shouldn't be presented as a model of R programming for beginners and that will cause headaches.
For example, they use 'setwd()' in a lesson, e.g.. But [friends don't let friends use `setwd`](https://plantarum.ca/code/setwd/). This is a time bomb in any code. Especially if they're submitting code that will only run in RStudio anyway (`View()`), they should just big the bullet and explain projects.

This is also not a good introduction to mapping census shapefile data in R. It uses a self-downloaded shapefile instead of using [`tigris`](https://rdrr.io/cran/tigris/man/tracts.html) to obtain census tracts; and it uses some custom dataset distributed by the Robert Wood Johnson foundation instead of using [`tidycensus`](https://walkerke.github.io/tidycensus/articles/basic-usage.html). If students are going to do change-across-time work in R, they would be much better served learning shared tools that will work more easily in a city other than Miami.

One really weird thing here for me is the import of `dplyr` at pp 66 just--as far as I can tell--to use its `select` function. This is weird; the later lines spent enormous amounts of code doing something that could be done much easier using dplyr's `rename` or `mutate`. Or by using a function three times, rather than repeating the same operation. 

Inside pp 70 there is an R markdown block, which is just a typo but, again, makes me concerned.


## Generalizability

This code will not generalize well. Geospatial analysis for students always falls apart with CRS strings. This code doesn't really explain them, and I had trouble understanding why they're using WKID 2777 for plotting here. (Why not just use EPSG:3857 if this is for other people? Am I missing something about tmap). They have users check that their current datasets *aren't* project, but what would you do if you *were* working with projected data?

The maps made using `tm_shape` are filled with all sorts of extremely custom parameters for this project that wouldn't even be right for obesity maps in other cities, let alone generalized mapping applications.

Take, for example, this code block:

```r
LegOb <- tm_shape(CT_City_Miami_Obesity)+ 
tm_fill("OBESITY_2018", title="PREVALENCE OF OBESITY\nIN MIAMI", size=.4, textNA = "No Data", colorNA = "white", style="fixed",breaks=c(0,20,30,40,50), labels=c("< 20%", "20.01 to 30%","30.01 to 40%","40.01 to 50%"),palette = "BuGn") +
 tm_borders(col="black") + 
tm_layout(legend.frame=F, legend.only =T, legend.position=c(0.45,0.2), scale=.9, title.position = c(0,0))

```

The in-text description is: 

> In the following code, which creates the legend, in the title, the “\n” creates a new line for the legend title. In this case, it aids in creating better legibility when all map objects are combined.

In no world is the most confusing part of the above code the newline character. I think I understand the arguments to these functions, but even the basic idea (using `+` to add together elements) is going to be confusing to those who don't use ggplot. And only after pasting it did I realize that students who try to copy-paste this code could easily end up changing the color breaks in the map panels but not in the legend, or even in a few of the maps and not in others.


## Duplication

This partially duplicates, as said, an existing PH lesson. It also conflicts with an excellent free online text on geocomputation at [https://geocompr.robinlovelace.net/intro.html]; although that is much longer, I think most of the pieces in there (such as a vastly expanded exploration of CRS formats) will be necessary for students to do their own projects.

The thing that makes this useful for **historians** other than those projects is, I guess, that it's change over time? But obesity in Miami during the Trump administration isn't a topic that fits within the history discipline, so I don't really see what the value-added here is, even if this tutorial becomes nearly perfect.

**Comment by hepplerj** [comment] 2020-03-18 15:22
## Overall

Overall, I think the piece needs quite a bit of work to be brought up to PH standards. They can be summed up as: 

1. Generalizability: How can users apply the objectives of this lesson to their own work? 
2. Applicability: How can historians use what's taught here for their own work?
3. Clarity: Who is the audience? Is the code and explanation clear enough for readers?

### Generalizability 

I have significant concern about how generalizable and thorough the code is for novice learners. There's things happening in the code that will completely lose novice users, and things happening that intermediate R users should know better than to do (don't be using `setwd()` -- better to probably introduce readers to RStudio projects instead). 

There's a lot of jumping around between Tidyverse methods and Base R methods that I think will absolutely lose novice users. Given that the writers end up using `dplyr`, at least for a moment, later in the lesson, it's not clear to my why we're not just using `sf` and `ggplot` for everything here. It would certainly simplify much of the code and provide 1) more opportunities for explanation, and 2) make the work more reproducible.

I also think there are parts of this lesson that overlap greatly with [a previous PH lesson](https://programminghistorian.org/en/lessons/geospatial-data-analysis), which also uses R and, I think, explains and _shows_ things more clearly to readers.

Lots of the code here lacks a lot of explanation that's really needed. Take this code for example at P83: 

```
tm_shape(CT_City_Miami_Obesity) + 
tm_fill("OBESITY_2016", title="Prevalence of Obesity", textNA = "No Data", colorNA = "white", title.size=1, style="fixed", breaks=c(0,20,30,40,50), interval.closure = "left", labels=c("< 20%", "20.01 to 30%","30.01 to 40%","40.01 to 50%"), palette = c("gray80","gray60", "gray47","gray15")) + tm_borders(col="black") +  
tm_layout(frame=F,main.title = "Prevalence of Obesity by Census Tracts in Miami, 2016", main.title.size = 1, legend.outside = TRUE, legend.outside.position = "right", legend.outside.size = .4, outer.margins = c(0.2,0,0,0))
```

There is zero explanation about what's happening in this block of code, much of which is quite custom for `tmap`. I have some familiarity with working with `tmap`, and even I have to stop and read closely what's happening here. For a novice user? Speaking from experience, they're going to be completely lost. 

I can also say that, having just taught my own workshop on making maps in R, one of the biggest issues people fumble over (myself included) with doing geospatial work is projections. Why are we using WKID 2777, for example? Why not EPSG:3857, which we see a more commonly and especially for web maps? What if a reader is working with data that's already projected? (You only talk about map data that has no projection, but what if their shapefile _is_ projected? -- this is the point where you will lose readers). I know this lesson isn't designed to be an introduction to GIS, but there's a lot of assumed knowledge about what's going on here (and, frankly, given the objectives of this lesson much of this could be more easily completed in ArcGIS or QGIS). 

## Applicability 

I think the biggest detraction for this lesson is it's **applicability for historians**. I'm just not certain that historians will take the examples here and (forgive the pun) map it onto their own work. There's a lot about the code snippets here that is difficult to parse. Not to mention that historical mapping comes with a lot more contingency versus data collected systematically by the CDC in recent years. That contingency of historical data is harder to map and explain, but in my experience more worthwhile for researchers and students.

I think Census data works decently well for general audiences being introduced to R mapping (it's the way I teach mapping in R for general audiences), but for the purposes of The Programming Historians I think this misses the mark. Given the availability of historical data in R (through something like [historydata](https://docs.ropensci.org/historydata/)) the lesson here could be made more applicable to historians, but it will take work. 

## Clarity

Overall, there are parts that lack the depth that is really needed -- and I think that, in part, is a reflection on who the audience is for this piece. Is it novice users or intermediate users? Historians or a general audience? The lesson says at the outset that it's for novice users (P1), but then says it's for intermediate R and GIS users (P9 P10). So which is it? I think there's a lot of switching between assumed knowledge and detailed knowledge in the piece, and it reads a bit unevenly because of it. As the piece stands, I wouldn't find much value in sharing it with my students or colleagues.  

## Miscellaneous comments

These are notes for paragraph (P#) level comments: 

- P16: Mac/Linux uses forward slash for directories, not backslash as written here. 

- P26: Explain CRS? 

- P38-P40: Lesson explains at the outset that it's for intermediate knowledge of R. If that's the case, why are we spending time on `View()`? R users will know what this is, and will probably use something else to explore this anyway (like `glimpse()` or `str()` or `names()`). 

- P40: What is a "slot"? Do you mean variables of the dataframe? 

- P42: Should you show the output of `proj4string` here?

- P56: Again, is this for novice users or intermediate users? Novice users won't have any idea what's happening here in this bracket subsetting without explanation. 

- P67-P69: Why are you using `colnames` and not `mutate()`, which you just loaded by calling on `dplyr`? I think this switching back and forth between **Base R** methods and **Tidyverse** methods will be confusing to readers. 

- P70-71: Some formatting issues with the code (```R is visible).

**Closed** 2020-09-27 16:18 UTC
Labels: English, submission
